import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import { cn } from "~/lib/utils";

const font = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn("bg-[#0C0C1D] text-[#D3D3D3]", font.className)}>
        {children}
      </body>
    </html>
  );
}
